### ISSUE TITLE
How to build and use this jar.

### ISSUE THREAD

**Issue by kapilsahu91** [mc1arke/sonarqube-community-branch-plugin#10]
When building the it complains that the manifest is absent in the created jar. Tried pointing main class to the com.github.mc1arke.sonarqube.plugin.CommunityBranchPlugin without any success.

**Comment by nixel2007** [comment]
how do you build it? `gradlew build`?

**Comment by mc1arke** [comment]
If you're just aiming to use the plugin then download it from the [repository's releases page](../releases).

For building the plugin, `./gradlew clean build` will generate the necessary JAR in `build/libs` which is what you should install to your SonarQube instance's `extensions/plugins` directory.

Performing `unzip build/libs/*` and then checking the contents of `META-INF/MAINFEST.MF` shows the lines I would expect, including a reference to the Plugin's main class:
 ```
Plugin-Class: com.github.mc1arke.sonarqube.plugin.CommunityBranchPlugi
 nBootstrap
```

Be aware that the Main class of the Plugin has to be set to `com.github.mc1arke.sonarqube.plugin.CommunityBranchPluginBootstrap` otherwise SonarQube will fail to load the plugin. See the Javadoc on that class for full details.
