### ISSUE TITLE
Publishing detailed guides

### ISSUE THREAD

**Issue by rverma-jm** [mc1arke/sonarqube-community-branch-plugin#146]
Can we maintain a detail guide on how to configure this plugin to make PR decoration work for Github/Gitlab/Bitbucket etc? I see like me, there are plenty of people struggling with making this work. (My story of struggle is at https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/129)

It would be nice those who have used the plugin successfully can contribute with their configurations and workflow, common troubleshooting steps etc...

**Comment by BobbyJohansen** [comment]
I would agree with this. I have the plugin installed but am struggling quite a bit to get it to decorate prs.

**Comment by mclayton7** [comment]
@mc1arke What's the best way to contribute to the documentation? Merge requests for README.md? I'm not sure of a good way to update the wiki.

**Comment by mc1arke** [comment]
@mclayton7 I believe you should be able to clone the wiki through https://github.com/mc1arke/sonarqube-community-branch-plugin.wiki.git and publish updates that way. I'd rather the README wasn't the primary source of documentation.

**Comment by irishfolk** [comment]
on my journey to getting this this and bitbucket play along together i came by here ... and made a new account to interact

@mc1arke would it be feasible to just enable the "wiki" feature for this repo? i would be willing to contribute by adding (to be found) knowledge of my bitbucket integration into such a wiki

because concerning the repo you mentioned https://github.com/mc1arke/sonarqube-community-branch-plugin.wiki.git 
* i first tried to access it via browser, which gave me a 404
*  then i cloned it on the cmdline (which worked, to my surprise), 
* then i looked into it to find it more or less empty. 
* then i added a dummy line and tried pushing which resulted in

`remote: Permission to mc1arke/sonarqube-community-branch-plugin.wiki.git denied to irishfolk.
fatal: unable to access 'https://github.com/mc1arke/sonarqube-community-branch-plugin.wiki.git/': The requested URL returned error: 403`

please go lightly on me if i am doing smth obviously wrong, just lecture me!

**Comment by mc1arke** [comment]
Given the plugin attempts to match the features in the Sonarqube documentation then my preference is that we direct people to use the relevant version of the Sonarqube docs, although I have re-enabled the Wiki on this repo if anyone does want to write some user guides.
