### ISSUE TITLE
Quality Gate is green despite multiple major issues while scanning Azure Devops pull request.

### ISSUE THREAD

**Issue by kikuingithub** [mc1arke/sonarqube-community-branch-plugin#176]
Hi ,

First of all kudos to the great plugin !!
I see the **Quality Gate is green despite multiple issues while scanning **Azure Devops Pullrequest.**** The code to be scanned is in python. **The long living branch pattern is .***
Sonarqube community edition version - Version 7.7 (build 23042)
Sonarqube-community-branch-plugin - 1.0.2
here are the steps to replicate this.
1. Create feature branch with high severity violaitons to detect from master of the code to scan
2. Create a pullrequest from feature branch to master
3. Scan the master branch prior to PR analysis.
4. Scan the Pullrequest .
5. See if the feature branch scan quality gate fails or not.

The expected behavior is that the Pullrequest scan Quality Gates should go red as mutiple violations are found during sonarqube scan.

Am i missing any configuration or something ?
Let me know if any more information is needed.

Thanks !!

**Comment by mc1arke** [comment]
This plugin doesn't perform any of the actual anlysis, this is managed internally in the Sonarqube compute engine. Your issue is likely to be due to the number of issues created versus the percentage of the codebase that's changed (or a small number of lines being modified), and can't be controlled through this plugin. I'm therefore closing this as invalid, although if you can provide a  Git repository with a base and updated branch that demonstrate this then I'm happy to confirm if you can overcome the issue by changing Sonarqube settings.

**Comment by kikuingithub** [comment]
Thanks for the quick turn around. I found the issue is with improper
quality gate. It is fixed now.
