### ISSUE TITLE
The plugin does not work with Sonar 7.8

### ISSUE THREAD

**Issue by BangBoy** [mc1arke/sonarqube-community-branch-plugin#19]
With https://github.com/SonarSource/sonarqube/commit/81638702d68033ca95ddd406aa655fb2bfdab036 in recent Sonar release (7.8), 

`targetScmBranch` in `org.sonar.scanner.scan.branch.BranchConfiguration` is renamed to `targetBranchName`

Can we just replace the name?

**Comment by mc1arke** [comment]
Thanks for the heads-up. Rather than just rename the method, I'd propose that an approach is used similar to the `generateKey` methods in `com.github.mc1arke.sonarqube.plugin.ce.CommunityBranch` where we introduce the new method without an `@Override` annotation, chain the old method to the new method and add comments to make it clear what versions each method is aiming to support.

I'll try and get a SNAPSHOT build containing this approach created and tested today

**Comment by BangBoy** [comment]
That sounds way better than what I suggested. Thank you!

**Comment by mc1arke** [comment]
#20 opened with my proposed fix. As detailed in the commit message, my proposed approach of maintaining backwards compatibility was not possible due to incompatible API changes in SonarQube, therefore the next version of the plugin will not support anything before SonarQube 7.8. I'll attach a SNAPSHOT build of the plugin to the Pull Request for people to test with and, if no-one raises issues with it in the near future, I'll merge the Pull Request and create a formal release.

**Comment by mc1arke** [comment]
Fix released in v1.1.0
