### ISSUE TITLE
mutual TLS for PR decorating

### ISSUE THREAD

**Issue by semox** [mc1arke/sonarqube-community-branch-plugin#195]
Dear all,

our bitbucket server api is secured additionally by mutual tls.
I tried to enable mutual TLS by applying 'javax.net.ssl.keyStore' and others params but it still fails.

Are there any plans to also support this feature? See https://github.com/square/okhttp/issues/1711

**Comment by mc1arke** [comment]
@semox This sounds like a very specialist use-case so not one that we're likely to build directly, unless Sonarqube provides a user interface (and associated code interfaces) to allow users to manage this. Part of the issue here is that I have to test the plugin as part of a release and this adds a fairly significant overhead to testing.

Given the lack of other reactions on this issue, I can't see high demand for this feature so am going to close this issue as a "won't do", but am happy for it to be re-opened if enough people feel this feature would be useful.
