### ISSUE TITLE
The 'project' parameter is missing (api/alm_settings/list?)

### ISSUE THREAD

**Issue by alekssako** [mc1arke/sonarqube-community-branch-plugin#208]
**Describe the bug**

**To Reproduce**
1. Go to 'Everywhere on page refresh'

**Expected behavior**

**Screenshots**

![Annotation 2020-07-16 183843](https://user-images.githubusercontent.com/26377888/87698560-f1425e80-c793-11ea-9128-ea647d6e2e8a.png)

**Software Versions**
 - SonarQube Version: [8.3.0.34182 / 8.3.1.34397 / 8.4.0.35506 / 8.4.1.35646]
 - Plugin Version: [1.3.2-SNAPSHOT]
 - Plugin Version: [[PR #202 ](https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/202)]

**Additional context**

Error on json response : `api/alm_settings/list?` : `{"errors":[{"msg":"The 'project' parameter is missing"}]}`

Possible fix change into : `api/alm_settings/list_definitions`. (Maybe)

**Comment by nixel2007** [comment]
It's a bug in 8.4.0, upgrade to 8.4.1

**Comment by alekssako** [comment]
@nixel2007 already done that but it still remains, removing the plugin it works but when adding the plugin the bug shows again.

![Annotation 2020-07-17 094133](https://user-images.githubusercontent.com/26377888/87761581-ffcf5b00-c811-11ea-84de-0817146c8efb.png)

**Comment by Rory898** [comment]
This plugin doesn't support sonarqube 8.4 yet
It unofficially supports 8.3 with the branch https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/sq-8_2-support

**Comment by alekssako** [comment]
@Rory898 Yes i know everything works like a charm, but that's an annoying thing.
I suppose this started since the api alm change on 8.3 : https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10930&version=15640

> [SONAR-13320](https://jira.sonarsource.com/browse/SONAR-13320) - api/alm_settings/list endpoint should be accessible with 'Administer project' permission

Considering this is a bug from 8.3+ and hopefully having a fix for the next release would be great.
Thanks in advance.

**Comment by mc1arke** [comment]
The `project` parameter on the `alm_settings/list` API endpoint is now optional according to the Sonarqube API docs, although I'm sure it was listed as mandatory in 8.2 if I set the `required` flag on it. I've updated the endpoint to make the parameter optional since we don't use the value anyway and pushed the change to the sq-8_2-support branch. Shakedown on 8.2 and 8.4 both didn't show any issues, so please give it a go and provide any feedback.

**Comment by eberhm** [comment]
The error notification is still showing.

![image](https://user-images.githubusercontent.com/1044082/88167860-63da9080-cc11-11ea-9112-9f0916bf9481.png)

Sonarqube version: Community Edition Version 8.4.1 (build 35646)
Community branch plugin version: 1.4.0

I understand the plugin does not supports officially Sonarqube 8.4 and that this issue is closed but just for the record ;)

**Comment by mc1arke** [comment]
1.4.0 of the plugin doesn't contain this fix, it's the unreleased version from master that you need to be using.
