### ISSUE TITLE
Support for Gitea PR annotations

### ISSUE THREAD

**Issue by lafriks** [mc1arke/sonarqube-community-branch-plugin#241]
If there is anything missing in Gitea API I would be more than happy to help with.

**Comment by mc1arke** [comment]
As you've seen on the responses to the Sonarqube tickets you've raised, this feature is impossible without forking Sonarqube since the UI, API, and enumerations are restricted to Gitlab, Github, Bitbucket, and Azure DevOps. I'm therefore going to close this request, although am happy to collaborate with you on creating a Sonarqube fork with the features that you need should you want to go down that road.

**Comment by lafriks** [comment]
yeah, it was quite disappointing from their side :(
I was thinking would it be possible to fork only lib part needed for plugin for this to work?

**Comment by mc1arke** [comment]
There's not really a small part you can fork with Sonarqube: it's all-or-nothing really. Since the introduction of a new provider would only make sense if it can be configured through the UI, there's no change we could make just by somehow managing to tweak things like the enum on its own.

I'd be more than happy to do some work on refactoring the Sonarqube codebase to make adding new providers easier, but I suspect that Sonarsource would push back on this given they don't seem to want to add more providers.

**Comment by lafriks** [comment]
yeah, they most probably wont accept that anyway :(
I know but I was thinking if library built with extended enum would work with standard sonarqube but plugin using custom library jar?
UI for configuring provider etc could be built in plugin as custom admin page than
