### ISSUE TITLE
unable to use with github

### ISSUE THREAD

**Issue by achuet** [mc1arke/sonarqube-community-branch-plugin#250]
Could anyone tell me how to use this plugin with github

**Comment by mojtabye2** [comment]
please explain what is the issue exactly.

**Comment by achuet** [comment]
I installed this plugin in sonarqube community edition. But I don't have any idea how to configure/use this to decorate github pr

**Comment by mc1arke** [comment]
I'm closing this since it doesn't contain enough detail to provide any realistic support. If the plugin is installed then you'll see relevant options in the Sonarqube admin screens. If you believe something isn't working then please ensure you provide details about what version of the plugin, the version of Sonarqube, and any configuration you've tried.
