### ISSUE TITLE
Support for SonarQube v8.8.0

### ISSUE THREAD

**Issue by stevehipwell** [mc1arke/sonarqube-community-branch-plugin#324]
Has the latest `v1.7.0` release been tested with _SonarQube_ `v8.8.0`?

**Comment by mc1arke** [comment]
Yes. It's had the basic testing of scanning a new project and an existing project, both with and without branch parameters to ensure the results were correctly rendered in Sonarqube. The configuration of bindings for PR/MR decoration has also been tested to ensure correct validation of inputs, although the actual PR decoration has not been tested as part of this release.

Do you have an issue to report with part of the functionality against 8.8?

(side note: this question may have been better asked under discussions rather than as an issue)

**Comment by stevehipwell** [comment]
Thank you for the quick response @mc1arke, I don't have a bug to report but I got caught out by v1.6 on SonarQube v8.7 so I was being proactive.

Sorry I missed the discussions tab, if I'd seen it I would have used that.
