### ISSUE TITLE
Do not display pull request decoration

### ISSUE THREAD

**Issue by epayco** [mc1arke/sonarqube-community-branch-plugin#337]
**Describe the bug**
Do not display pull request decoration
No token could be found with access to the requested repository with the given application ID and key
 i'm using github.com

![imagen](https://user-images.githubusercontent.com/16478484/115054567-f9a40300-9ea5-11eb-8e15-4fb6fa07d226.png)

**Software Versions**
 - SonarQube Version: 8.4
 - Plugin Version: 1.5

Can please you help me?

**Comment by epayco** [comment]
I try with a new repository in log there's no error but still not showing the pull request decoration
![imagen](https://user-images.githubusercontent.com/16478484/115062546-147b7500-9eb0-11eb-87da-4a2a713c6e8c.png)
![imagen](https://user-images.githubusercontent.com/16478484/115062626-2bba6280-9eb0-11eb-9c22-ecf3389913c4.png)

**Comment by mc1arke** [comment]
Closing since the reporting user no longer exists.

The screenshot indicates a check run has completed which is what is expected. and no comment will be added unless summary comments are enabled. The initial error would be due to the app used for Sonarqube to connect to Github didn't have permissions for the target repository.

**Comment by juanMarulanda** [comment]
the user not exist because mow is an organization.... we confiogured all permisions for the app and the comment is activated... but it shoud wiork with old repositories

**Comment by juanMarulanda** [comment]
![image](https://user-images.githubusercontent.com/42282835/116110820-a71fcf00-a67b-11eb-9272-333e6ccb4441.png)

**Comment by juanMarulanda** [comment]
@mc1arke

**Comment by mc1arke** [comment]
@juanMarulanda you'd need to enable debug logging for the Compute Engine and submit an analysis so I could see the detail of which decorators ran, and what the requests and responses were for those decorators.

**Comment by Logicoeur** [comment]
@mc1arke how do you enable debugging for the CE? I am hitting a decorator error with that "no token found with access to xxx repository" error. I believe it is due to SAML on the GHE instance as I've tried to replicate calling the Github v3 apis to authenticate as a github app and am redirected to our SAML login. Haven't yet found a way to get the entire stacktrace in the sonar service logs, or how to get through/around saml as a github app.
