### ISSUE TITLE
Failed to find Premain-Class manifest attribute

### ISSUE THREAD

**Issue by chakrapani123** [mc1arke/sonarqube-community-branch-plugin#370]
hello,

I have noticed following error when installing 1.7.0 plugin on sonar 8.8 version on Centos7

plugin version - sonarqube-community-branch-plugin-1.7.0.jar
sonar version - 8.8

error message:

Failed to find Premain-Class manifest attribute in /app/sonarqube-8.8.0.42792/extensions/plugins/sonarqube-community-branch-plugin-1.7.0.jar

thanks
chakri

**Comment by mc1arke** [comment]
1.7.0 of the plugin uses different installation instructions which don't involved setting the plugin as an agent on the JVM. See https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/1.7.0#installation for details of how to install 1.7.0, although also consider updating to Sonarqube 8.9 since it's the latest LTS.
