### ISSUE TITLE
GitLab: mono repo support

### ISSUE THREAD

**Issue by qqshfox** [mc1arke/sonarqube-community-branch-plugin#377]
Hi,

Thank you for the awesome work. I was trying to use pull request decoration in our monorepo which is hosted on a self-hosted GitLab. However it didn't seem to support this usage. The decorator will delete all notes despite which project they belong to. I did find a merged PR to support GitHub but no GitLab yet. I'm wondering if there's a plan to support pull request decoration for gitlab monorepo?

I'm reading the code and it seems to lack project key for the notes created by decorator. Thinking to add the project key as a part of analysis result and file comments, and extract them by parsing note text for the next run. But not really a fan of parsing raw text. Not sure if there's other way to do this. Would you give me some suggestions? Thanks.

**Comment by mc1arke** [comment]
Hi, thanks for the question!

As I'd done some initial work on the Gitlab decorator to retain and resolve discussions rather than deleting and recreating comments, which parsed the issue ID from the link we put in each comment, I've tidied up and pushed that work in #382. This has introduced the pattern you're asking about of parsing text, and allowed it to be performed fairly trivially whilst retrieving issue IDs, so I've pushed a change for it in #383. Please take a look and provide any comments, and if possible try out a the Snapshot build for that second MR and provide any feedback on how it works.

**Comment by qqshfox** [comment]
Thanks a lot for implementing this so fast! I've tested #383 and it works great 👍 .

1. Creating summaries ✅ 
2. Creating hotspots ✅ 
3. Resolving summaries without comments ✅ 
4. Resolving hotspots without comments ✅ 
5. Leaving summaries with comments open ✅ 
6. Leaving hotspots with comments open ✅ 
7. No redundant SonarQube comments ✅ 

One minor suggestion only, would you add a project name in the summaries please, so that we could tell which sonarqube project it belongs to easily instead of hovering the `View in SonarQube` link to look for the project key? Thanks.

**Comment by mc1arke** [comment]
Thanks for the comprehensive testing! As you've suggested, I've added the project ID into all comments (summary and individual issues), and issue IDs into the issue comments.

**Comment by qqshfox** [comment]
Thank you so much! It looks perfect!

**Comment by mc1arke** [comment]
Release in v1.9.0 of the plugin

**Comment by mc1arke** [comment]
Backported to 1.8.1 of the plugin for Sonarqube 8.9 support.
