### ISSUE TITLE
New Code: "reference branch" considers only commits after last merge

### ISSUE THREAD

**Issue by Hanseter** [mc1arke/sonarqube-community-branch-plugin#449]
**Describe the bug**
When you're using the "reference branch" option for the "New Code" calculation it does not behave like described in the [docs](https://docs.sonarqube.org/8.9/project-administration/new-code-period/). According to them *Any changes made from your reference branch are considered New Code*. However the real behaviour is that the analysis only takes code (commits) into consideration that were created after the last time the reference branch was pulled into the working branch.

**To Reproduce**
1. Create branch "a" with reference branch "master".
2. Create 5 commits on branch "a".
3. Create 1 commit on branch "master".
4. Merge "master" into "a".
5. Perform analysis on branch "a".
6. _Error:_ Analysis identifies no new code, even though there are 5 commits difference.
7. Create 3 new commits on "a" and perform analysis.
8. _Error:_ Analysis identifies only the last 3 commits as new code, even though there are 8 commits difference.

**Expected behavior**
All differences between analysed branch and reference branch should be considered "New Code".

**Software Versions**
 - SonarQube Version: 8.9.2 (build 46101)
 - Plugin Version: 1.8.1

**Additional context**
Depending on your workflow this issue might or might not be a problem. In our workflow we always merge the latest "master" state into a feature branch, before review and merge. Which means that for a while now all our feature branches had no new code when being reviewed.

**Comment by mc1arke** [comment]
Are you able to try and test with Sonarqube Developer edition to see if it works are you'd expect?

The plugin doesn't actually provide any input to the Compute Engine when it's performing an analysis (however there may be something I've not implemented which would influence the identification of changes), so I'm not sure if this is just an issue in the way Sonarqube works.

**Comment by Hanseter** [comment]
Unfortunately I do not have access to a Developer Edition.

I will see if I can get access to one or maybe try to install one locally.

**Comment by MarcelT-NL** [comment]
+1

We use a master and development branch and would LOVE to have the issues synchronized!

**Comment by mc1arke** [comment]
I think this is actually a bug in Sonarqube's Git SCM provider, specifically in the [`forkDate` method](https://github.com/SonarSource/sonarqube/blob/a8abcbdb23a8558c281739ef23f355993eb07162/sonar-scanner-engine/src/main/java/org/sonar/scm/git/GitScmProvider.java#L217) which calls [`findMergeBase` ](https://github.com/SonarSource/sonarqube/blob/a8abcbdb23a8558c281739ef23f355993eb07162/sonar-scanner-engine/src/main/java/org/sonar/scm/git/GitScmProvider.java#L339) to find the last common commit between the 2 branches, and extracts the timestamp from that commit for later use in filtering issues in the report. The use of `findMergeBase` means the last merge of `master` onto `branch_a` is treated as the common branch point, even though `branch_a` has additional commits that were created before this merge point that aren't common to the `master` branch, but as their findings timestamps pre-date the last merge timestamp, those findings are excluded from the report.

I don't think there's any way to resolve this in the plugin as Sonarqube doesn't store findings against SCM metadata, so even if the SCM provider was to continue to RevWalk through `branch_a` to find all non-merged commits there would be no way of Sonarqube then excluding findings from interim commits, or the commits from `master` would end up being included in the findings report for `branch_a` since they'd appear as being on `branch_a` once they're included in the same branch after the point the initial commit that was made only to `branch_a`.

Given this information, I'm closing this issue as "Won't fix" as I believe this is outside the scope of what this plugin provides.

**Comment by mc1arke** [comment]
This should be fixed in Sonarqube 9.3 with [the resolution ](https://github.com/SonarSource/sonarqube/commit/3ec97d1a4368fdd3212d524aacfc73403ed709ce) of [SONAR-14929](https://jira.sonarsource.com/browse/SONAR-14929)
