### ISSUE TITLE
GitLab Pull Request Decoration: Adding new commits doesn't update decoration(s)

### ISSUE THREAD

**Issue by Smithiess** [mc1arke/sonarqube-community-branch-plugin#537]
Versions:
- Community Edition Version v8.9.6
- sonarqube-community-branch-plugin v1.8.1

Thank you very much for your work on the sonarqube-community-branch-plugin!

I was wondering about the following situation:
- I open a merge request / pull request on GitLab
- SonarQube runs successfully and marks all smells/bugs as comments and additionally as a final summary.
- Now I add a commit, either by "git commit + git push" or "git commit --amend + git push --force".
- The GitLab pipeline runs again, SonarQube runs successfully as well and new bugs, if any, can be seen in the SonarQube UI.
- However, no additional comments appear / the summary stays the same and doesn't show that new bugs have been introduced with the new commit.

What can I do to update the summary / comments in GitLab?

Thanks!

**Comment by mc1arke** [comment]
The `--amend` and `push --force` workflow is one I use daily with one of the companies I work with and get new/updated issues reflected in Gitlab. Can you confirm whether you're getting any errors appear in the Sonarqube CE logs for a failed decoration?

**Comment by phermsdorf** [comment]
Hi,

we use the same versions and use a workaround.
Please see
* https://jira.sonarsource.com/projects/SONARJNKNS/issues/SONARJNKNS-315
* https://groups.google.com/g/jenkinsci-dev/c/-ojqklsaKbw/discussion
which describe the basic problem. 

We use the following script in our Pipeline to detect the correct commit for the SonarQube analysis and commenting:

```
script {
        if(env.CHANGE_ID != null) {
            // this hack is necessary to aquire the pr head commit id for sonar to comment on
            if(env.GITLAB_OA_LAST_COMMIT_ID) {
                env.COMMIT_ID="$GITLAB_OA_LAST_COMMIT_ID"
            } else {
                env.COMMIT_ID=sh(
                    script: """
                        curl -s --header "PRIVATE-TOKEN: ${JENKINS_GITLAB_TOKEN}" "https://gitlab.com/api/v4/projects/${projectID}/merge_requests/${CHANGE_ID}" | grep -Po '"sha":"\\K([0-9a-f]+)' | head -1
                    """,
                    returnStdout: true
                ).trim()
            }
            sh """
                mvn -f com.godyo.p5.releng/pom.xml ${SONAR_GOAL} -Dsonar.pullrequest.branch='"${CHANGE_BRANCH}"' \
                        -Dsonar.pullrequest.key=${CHANGE_ID} \
                        -Dsonar.pullrequest.base=${CHANGE_TARGET} \
                        -Dsonar.scm.revision=${COMMIT_ID} \
                        ${MAVEN_REPO} \
                            ${SONAR_MAVEN_CALL}
            """
        } else if (env.BRANCH_NAME == 'master'){
            sh """
                mvn -f com.godyo.p5.releng/pom.xml ${SONAR_GOAL} -Dsonar.branch.name=${GIT_BRANCH} \
                    ${MAVEN_REPO} \
                    ${SONAR_MAVEN_CALL} 
            """
        }
    }
```
That snippet was created by a colleague of mine and works for us. Hope that helps.
 
Bye Peter

Bonus Question: @mc1arke would it be possible to update an existing summary / comment when pushing newer commits instead of adding mutliple summary / comments which clutters the MR? (or should that work already and our workaround prevents that? Thx!)

**Comment by mc1arke** [comment]
@phermsdorf I presume you're using non-fast-forward merging on your MRs, as you generally should not need to work out the commit ID if checking out the branches or performing a FF-based merge as part of your Jenkin build.

We do actually resolve the existing discussion thread for the summary comment when creating a new summary comment, but Gitlab doesn't provide a way of collapsing the content of the resolved comment which is why the MR ends up looking cluttered. I don't want to edit the existing comment in place as Gitlab doesn't notify watchers of edited comments, and moved away from deleting comments due to it leaving orphaned discussions in previous versions of the plugin.

**Comment by phermsdorf** [comment]
> I don't want to edit the existing comment in place as Gitlab doesn't notify watchers of edited comments
In our case that would not be a problem. A configuration option to enable this behavior would be great.

**Comment by Nezteb** [comment]
> I don't want to edit the existing comment in place as Gitlab doesn't notify watchers of edited comments

Is it possible to have this as a configurable option? From what I can tell, that's the default in SonarQube developer/enterprise. If not a configurable option, is anyone aware of a way for us to hack this in via pipeline script? 😅 

Our MRs are frequently cluttered with several/dozens of resolved threads like these:
<img width="505" alt="Screenshot 2023-03-02 at 8 49 37 AM" src="https://user-images.githubusercontent.com/3588798/222508879-84877bac-479d-4141-a958-a22fb1b64f92.png">

We don't really use watcher notifications; we have a setup that requires SonarQube checks to pass before an MR can be merged, so it's pretty obvious to a developer whether or not they need to check the SonarQube results.

**Comment by Nezteb** [comment]
In the meantime in case anyone likes userscripts, here is one I made for Tampermonkey that will remove all resolved bot comment threads from your view: https://gist.github.com/Nezteb/141a1162ec0dbf72fe7aaeb4475ea44d 😄
