### ISSUE TITLE
Can this plugin can match sonarqube 8.9 or above?

### ISSUE THREAD

**Issue by andyzheung** [mc1arke/sonarqube-community-branch-plugin#624]
I use the sonarqube helm to deploy the sonarqube 8.9.8.
and want to use the this plugin, but seem to have some problem like the following:
![image](https://user-images.githubusercontent.com/22912347/174114534-eacf1696-e381-484e-b0dd-7c757bb072d3.png)

how to solve this problem on sonarqube 8.9 or above..
I see the version match table, can I change the sonarqube to the higher version to solve?
![image](https://user-images.githubusercontent.com/22912347/174114832-0f63a417-e443-4c5a-abf9-5ea913d3bd22.png)

**Comment by brother** [comment]
sonar-application states 9.0.1, are you sure it's really 8.9.8? Try the 1.9.0 plugin instead maybe?

**Comment by mc1arke** [comment]
As @brother has pointed out: your launch arguments indicate you're using Sonarqube 9.1 rather than the 8.9 you'd mentioned, so you'll need to use the associated plugin version. The error you're getting indicates the plugin could not be found at the path you've set in the 'javaagent' command attribute, so I'd suggest you check you're using a consistent version between download and the launch command.
