### ISSUE TITLE
Is there any way to disable starting thread on merge request?

### ISSUE THREAD

**Issue by emilebui** [mc1arke/sonarqube-community-branch-plugin#683]
**Describe the bug**
Hi, is there anyway to disable this? I have a case where a merge request has too many issues and it just floods our merge request with threads. I just need the analysis details comment, there is no need to create threads. I always view the issues on sonarqube portal so there is no need to enable this starting thread feature. If there anyway to disable it, pls tell me. Thanks!!
![Untitled](https://user-images.githubusercontent.com/33470772/198494917-6289c101-f418-43e3-9f32-76db60dcd77b.png)

**Comment by obriat** [comment]
I got the opposite problem: when there is no SonarQube issue, the thread status is set to unresolved (Gitlab MR).
No blocking, but a bit annoying.
Is it a bug a feature ? Should I open a separate issue ?

**Comment by DavidRotert** [comment]
Same Issue here. It can be really annoying and frustrating when introducing SonarQube into a team with a legacy codebase.

**Comment by mc1arke** [comment]
The plugin replicates what Sonarqube does, which is to report all issues. If you're not wanting issues reported then alter your quality gate (otherwise you're encouraging issue blindness) or raise a feature request against Sonarqube developer edition to allow filtering during decoration.

**Comment by mhagnumdw** [comment]
> The plugin replicates what Sonarqube does, which is to report all issues.

First, thank you very much for this plugin, @mc1arke

I tested sonarqube:`9.8.0-developer` with a trial license for more than a month. In GitLab's Merge Request, Sonar only posted a comment (not a thread) with the summary of the analysis. Issues reported by Sonar did not become threads in Merge Request. It's been about 3~4 months since I did this test and I still have the Merge Request history showing this. The user/token used by Sonar to access GitLab has a Developer level.

Today I decided to do a test with the sonarqube:`9.8.0-community` version (same version number) with the plugin in version `1.14.0` (according to the doc). Both the analysis summary and the issues reported by Sonar become threads in GitLab's Merge Request.

Do you know why this difference exists?

It would really be great if we had the option to choose whether threads should be opened or not in GitLab.
