### ISSUE TITLE
Allow override configuration from cli

### ISSUE THREAD

**Issue by artemy-osipov** [mc1arke/sonarqube-community-branch-plugin#72]
When an organisation has many repositories/projects, configuring projectSlug/repositorySlug for each one is quite exhausting. It would be nice to let specify these parameters from cli

ex:
```
docker run -ti -v $(pwd):/usr/src newtmitch/sonar-scanner:4.0.0-alpine \
  -Dsonar.host.url=$SONAR_URL \
  -Dsonar.projectKey="project:sample" \
  -Dsonar.projectName="sample" \
  -Dsonar.projectBaseDir=/usr/src \
  -Dsonar.sources=. \
  -Dsonar.pullrequest.key="13" \
  -Dsonar.pullrequest.branch="test-sonar" \
  -Dsonar.pullrequest.base="master" \
  -Dsonar.pullrequest.provider="BitbucketServer" \
  -Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.projectKey="project" \
  -Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.repositorySlug="sample"
```

PS I found similar solution from here https://community.sonarsource.com/t/post-analysis-task-only-when-scanner-parameter-set/12121.
If it fits, I can create a PR during the week.

**Comment by mc1arke** [comment]
Sounds like a reasonable suggestion.

I'd suggest that any parameters that can't normally be passed from the scanner engine use the `com.github.mc1arke` naming convention at the command line (e.g. `com.github.mc1arke.sonarqube.plugin.branch.pullrequest.provider` instead of `sonar.pullrequest.provider`) so that it's clear this a custom implementation. I'd also suggest these parameters are used only if the standard parameters haven't been set server-side (i.e. the command line can't be used to specify an alternative repositorySlug or provider if these have already been configured in the project).

**Comment by artemy-osipov** [comment]
@mc1arke why is it preferable to keep priority of parameters from server-side over parameters from the scanner? I think more specific parameters should have a higher priority. As far as I understand, the sonar itself works by the same principle according to https://docs.sonarqube.org/latest/analysis/analysis-parameters

**Comment by mc1arke** [comment]
Only some properties can be over-ridden from the command line, and none of them can result in information leakage. As some of our parameters potentially allow calls and information to be sent to third-party systems that the Sonarqube administrator hasn't explicitly approved, we want to ensure they don't allow data to be leaked. Providing we restrict which properties can be overridden (i.e. not API URLs, username, passwords, or keys) and consider the impact of a user being able to submit a misconfigured value, then I don't mind if we allow the scanner to take precedence.

**Comment by mc1arke** [comment]
Delivered as part of 1.3.0

**Comment by marvin-w** [comment]
Thanks for the contribution @artemy-osipov!

@mc1arke I understand the reasoning behind your decision to only allow certain parameters to be passed via CLI. At least from my perspective it would have been easier to implement certain CI/CD scenarios with the ability to override (almost) all parameters.

Whilst I understand your decision I'd like to propose an alternative approach to this. We could implement a feature flag that, when true, allows parameters from the CLI to override server parameters and, when false, does not allow overriding. Like toggling the evaluation priority. Or maybe just completely disable the CLI parameters if set to false.

**Comment by mc1arke** [comment]
I've got no issue with the proposed  approach, since it leaves the security options up to the server administrator to decide.

Be aware that part of bringing the 8.1 support branch up-to-date with the recent updates to master is currently removing the `UnifyConfiguration` class that allowed this override, since SonarQube 8.1 now reads and stores Pull Request decoration configuration and bindings in the database so didn't have obvious property names to override. I have no problem with someone working to re-introduce this type of setup if they can propose a suitable approach and options, but I'd probably propose you do any work in this area after I've pushed updated 8.1 changes.

**Comment by marvin-w** [comment]
That's a great hint. I will not do any work in that area for now then. At least not to master.

**Comment by srknkbs** [comment]
Hi @mc1arke and @artemy-osipov,

Which configuration parameters can we currently override from CLI?

We are trying to override the following parameters from our Jenkins pipeline groovy script but we haven't been successful yet.

```
-Dsonar.pullrequest.bitbucket.projectKey=<project key> \
-Dsonar.pullrequest.bitbucket.repositorySlug=<repository slug> \
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.token=<bitbucket access token> \
```

When we set these parameters from SonarQube server, we are able to decorate our pull requests. However, we have more than 20 repositories and it would be better for us to configure them in one place.

Thanks
Serkan

**Comment by artemy-osipov** [comment]
Hi @srknkbs 
There is naming convention to define overridable parameters. 
Parameters which starts with sonar.pullrequest.bitbucket can be set from CLI
Parameters which starts with com.github.mc1arke.sonarqube.plugin can be set only on server
