### ISSUE TITLE
Pull Request Decoration - Unknown url : /api/alm_settings/list_definit...

### ISSUE THREAD

**Issue by petacz** [mc1arke/sonarqube-community-branch-plugin#75]
**Describe the bug**
Hello,
When I want to setup Pull Request Decoration and I open the settings page, I get an error:
Unknown url : /api/alm_settings/list_definit...
[Screenshot](https://i.imgur.com/9AwOZwV.png) 
It seems that whole /api/alm_settings/ API prefix is missing in Community Edition of SonarQube.

**To Reproduce**
1. Go to Administration
2. Configuration
3. General Settings
4. Pull Request Decoration
5. See error at the top

**Expected behavior**
If Pull Request Decoration should be setup differently than it should be documented and maybe also mentioned that this error is expected when using Community Edition.

Is this a way how to setup Pull Request Decoration even in newer versions on SonarQube (7.8+)?https://docs.sonarqube.org/7.7/analysis/pull-request/#header-2

**Screenshots**
[Screenshot](https://i.imgur.com/9AwOZwV.png) 

**Software Versions**
 - SonarQube Version: Community Edition Version 8.1 (build 31237)
 - Plugin Version: [Pull Request](https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/58) and [Direct link](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/3987239/sonarqube-community-branch-plugin-1.2.1-SNAPSHOT.zip)

**Additional context**

**Comment by mc1arke** [comment]
The version of the plugin you've linked to doesn't have any Pull Request decoration features in it, so that screen isn't being managed by the plugin. I hadn't looked at the configuration options in 8.1, so will check if the PR screens are appearing due to something we're doing in our basic plugin installation.

**Comment by mc1arke** [comment]
Sonar 8.1 introduced various changes through SONAR-12512, SONAR-12513, SONAR-12512 etc to require new Web services to be present on server-side for configuring each ALM and binding it to a project. They also introduced the screens you're seeing which are made visible if branch functionality is available, which is detected by the presence of a class implementing one of the interfaces that's required for us to use the branch API. For us to properly support Sonar 8.1 and later versions, we'll need to implement these web services, and will probably need to update the various decorators to use the new ALM DAO to retrieve the relevant ALM configuration, rather than through the properties we're currently exposing.

**Comment by ramaprakashganesan** [comment]
This seems to be fixed for GitLab - [https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/87](url).
Any way to get this to work with GitHub Enterprise?

**Comment by Baben01** [comment]
Hi, 

I get the same error when I try to configure Gitlab access with the latest release of this plugin (1.3.0) and Sonarqube 8.1.0.3123. 

Thanks !

**Comment by mc1arke** [comment]
@Baben01 SonarQube 8.1 isn't supported by 1.3.0 of the plugin. #58 contains proposed changes for working with 8.1, and will shortly be bought up-to-date against recent changes in master.

**Comment by mc1arke** [comment]
Version 1.4.0 of the plugin has been released with support for Sonarqube 8.1, which provides the required APIs for supporting the new ALM bindings that Sonarqube core is looking for when branch features are enabled.
