### ISSUE TITLE
Default main branch always "main"

### ISSUE THREAD

**Issue by usinelogicielle** [mc1arke/sonarqube-community-branch-plugin#800]
**Describe the bug**
In SonarQube documentation for SonarQube LTS 9.9 : https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/branches/branch-analysis/#main-branch 

They say that SonarQube, the main branch is the analysis with no option for specific branch.
But with the plugin sonarqube-community-branch-plugin v1.14.0.
The main branch in SonarQube is always "main".

**To Reproduce**
1. Create a Git repository with "master" branch name
2. Launch sonar-scanner with no option "-Dsonar.branch.name" : 
``` 
sonar-scanner  -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300
```
3. Wait the end of analysis and check the branch name

**Expected behavior**
The main branch of SonarQube is named "master"

**Screenshots**
![image](https://github.com/mc1arke/sonarqube-community-branch-plugin/assets/73827301/c359300f-1095-4df7-a6a2-823191ecd26b)

**Software Versions**
 - SonarQube Version: 9.9.1 Community EditionVersion 9.9.1 (build 69595) (Docker)
 - Plugin Version: 1.14.0installed (manually installed)
 - sonar-scanner : 4.5.0.2216 (docker)

**Additionnal context**

There is no code to analyse. Only check the branches

**Comment by jvmdc** [comment]
As a workaround, you can set `sonar.projectCreation.mainBranchName` to `master` so all new projects are created with `master` as the default branch

**Comment by davidIglesiass** [comment]
In my case only make the analisys in the master branch :c

**Comment by rnoberger** [comment]
Since the SonarQube Release 10.2 you are able to change the default branch after the project initiation:

https://www.sonarsource.com/products/sonarqube/whats-new/sonarqube-10-2/#flexible-main-branch-designation

In the documentation it is also described: https://docs.sonarsource.com/sonarqube/10.2/analyzing-source-code/branches/branch-analysis/

Before 10.2 you have to set the default branch in the global configuration. Keep in mind that this is a plugin that allows you to analyze multiple branches. So the documentation of sonarqube may not be the way the plugin behaves.

**Comment by mc1arke** [comment]
The ability to change the default branch name has been present since somewhere in the Sonarqube 8 compatible versions of the plugin, so I'd say this is working as expected.
