### ISSUE TITLE
SQ 10.3.0-community + plugin 1.18.0 got error "No branch exists in Sonarqube with the name"

### ISSUE THREAD

**Issue by fourirakbar** [mc1arke/sonarqube-community-branch-plugin#909]
**Describe the bug**
We submit a PR to a branch that doesn't exist in SQ (but already exists in the GitHub repo). For example, in SQ only the "main" branch is listed, while we submit a PR to the "develop" branch. Then, we will get an error "No branch exists in Sonarqube with the name."

Previously, we used Sonarqube version 9.3.0-community and plugin 1.12.0, everything ran normally and there was no error like this.

**To Reproduce**
1. Make a PR to a non-existing branch in SQ, let's say to branch "develop"

**Expected behavior**
1. Non-existing branch (develop) is created automatically in SQ
2. There is no error "No branch exists in Sonarqube with the name"

**Software Versions**
SonarQube Version: 10.3.0-community using helm chart
Plugin Version: 1.18.0
Sonar maven scanner version: 3.11.0.3922

**Additional context**
My code uses Java Spring (Maven). Meanwhile, I can solve this by adding `<sonar.branch.name>develop</sonar.branch.name>` in the pom.xml. The effect is that the "develop" branch will appear in SQ. Then I must remove `<sonar.branch.name>develop</sonar.branch.name>` from the pom.xml and make the PR again. This is quite inconvenient for us, because with the previous version I did not have to do this.

My problem might be similar to https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/854, but I still don't quite understand how to fix it.

**Comment by hballangan-mdsol** [comment]
@mc1arke having the same error. I would add that this issue raises more concerns as it's affecting a lot of repos doing lots of release branches.

Our CI before the change:
```
name: CI - Test Automation
on:
  workflow_dispatch:
  push:
    branches:
      - develop
```

For us to create custom branches, we now have to remove and let it run on all branches, which is a lot of wasted resources since we are already running on PR and also it will create a lot of useless branches (since we only need main, or release). Our last option is to totally disable code analysis if the target branch is NOT develop which is not ideal since we are doing a lot of release branches.
```
push:
    branches:
      - develop
```

Now I understand that the new feature added was to prevent errors at the start of code analysis if now main branch exists, but that error doesn't happen if the project has already been created and we just want to create new branch. Maybe a workaround for this is to only reject creating new project that starts with main/develop/master since those are the only branhces where we are actually creating a new project. If the branch name is different, most likely we are doing a PR analysis on custom/release branches then the code analysis should still be allowed and custom branch creation should push through. Why I suggest this is that we never encountered any error in the past for this case scenario.

**Comment by hballangan-mdsol** [comment]
For those encountering this issue on Github actions, a workaround is to add workflow dispatch:
```
on:
  workflow_dispatch:
```

And manually trigger the Code Analysis Github Action on the non-main branch. You have to do this for all non-main feature/release branch.

**Comment by maicaballangan** [comment]
Found that the feature for sonarqube includes autocreation of branches(see [provision github projects with ease](https://www.sonarsource.com/products/sonarqube/whats-new/sonarqube-10-3/#provision-github-projects-with-ease-and-flexibility)) when using the github action. So it is going against the direction of the upgrade if the community pull request is doing the opposite and restricting autocreation of branches

**Comment by maicaballangan** [comment]
> For those encountering this issue on Github actions, a workaround is to add workflow dispatch:
> 
> ```
> on:
>   workflow_dispatch:
> ```
> 
> And manually trigger the Code Analysis Github Action on the non-main branch. You have to do this for all new non-main feature/release branch.

**Comment by visu-suganya** [comment]
@mc1arke 
Thanks for your effort.
We had already configured community sonar branch plugin with `-Dsonar.pullRequest.base=develop` property in 9.9.
Then upgraded to 10.3 with branch plugin. But now pullRequest.base property is not working, Im getting errors from all the CIs wherever configured with this before.

Please let us know how to do workaround when using in github actions using sonarqube-scan-action and in circleci docker image.

**Comment by mc1arke** [comment]
> Non-existing branch (develop) is created automatically in SQ

This is where the problem lies: the plugin (or Sonarqube) doesn't know what's on that branch, so can't realistically report new/changed issues. 


> Found that the feature for sonarqube includes autocreation of branches(see [provision github projects with ease](https://www.sonarsource.com/products/sonarqube/whats-new/sonarqube-10-3/#provision-github-projects-with-ease-and-flexibility)) when using the github action. So it is going against the direction of the upgrade if the community pull request is doing the opposite and restricting autocreation of branches

I don't think the release note you've mentioned in your comment indicates anything about automatic creation of branches - only that Sonarqube will automatically configure project details (branch name and pull request decoration) for you.

If you can show evidence that demonstrates automatic scanning of a target branches on submissions of a scan then I'll happily investigate how to make the plugin work in the same way, but the current implementation is as it is to prevent misleading scans being presented to users.

> Then upgraded to 10.3 with branch plugin. But now pullRequest.base property is not working, Im getting errors from all the CIs wherever configured with this before.

I'm presuming you're getting an error stating that `No branch exists in Sonarqube with the name ...` when using `sonar.pullrequest.base`, which is intended if you haven't scanned the target branch.
