### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by bmaehr** [mc1arke/sonarqube-community-branch-plugin#99]
**Describe the bug**
The documentation about this great plugin is (even in in the wold of developers) really poor

**Expected behavior**
A clear and concise description what is working in which version and with which SCM and how to configure it

**Screenshots**
If applicable, screenshots would be very nice

**Additional context**
I tried to find out the status of this project for some months but failed until now even looking at the source code, the tickets and the branches. I have installed it (I think correctly) but still see no effect or in fact even don't know what effect to expect. I also try to configure the plugin but has no Idea how.

I try to write down my questions and perhaps answer them partially self in commets of this ticket. Hopefully the collection will be transfered at some point to the README (if mc1arke has time to merge branches and build releases)

**Comment by bmaehr** [comment]
1.) What does this plugin do (for the CE of Sonarqube)?
a.) Allow to analyze of a feature branch during a build (Is this supported by CE or just with this plugin?!?)
b.) Printing a link (Is this supported by CE or just with this plugin?!?) to display the analyzation results and displaying the results (I think CE is doing this) during the build
c.) Decorating the feature branch in SCM (Which version of the plugin supports which SCM?)

2.) Konfiguring the build
I was able to do a build with analyzation and get a link by building it with
`mvn sonar:sonar -Dsonar.host.url=http://sonar/ -Dsonar.java.coveragePlugin=jacoco -Dsonar.pullrequest.branch=origin/mybranch -Dsonar.pullrequest.base=master -Dsonar.pullrequest.key=1 -Dsonar.gitlab.project_id=mygroup/myproject -Dsonar.gitlab.commit_sha=8ae184c52086814e9c8b35eb7a5334478db1fb12 -Dsonar.gitlab.ref_name=origin/mybranch`

3.) Further configuration for decoration
a.) I didn't find any configuration settings inside the sonarqube web ui
b.) For gitlab I see some parameters like `com.github.mc1arke.sonarqube.plugin.branch.pullrequest.gitlab.url` somewhere in code but where have thes properties to be set?
c.) Is there a complete list of parameters and wher to set them?

**Comment by bmaehr** [comment]
@tritumMf according to your bug #93 you should perhaps to be able to answer/clarify some of the questions

**Comment by mc1arke** [comment]
@bmaehr The documentation up until now is purposefully limited because, as the README intimates, we're supporting the features provided by the Sonarqube interfaces we're implementing and are therefore directing users to read the Sonarqube documentation on branch management and configuration.

We're currently in an interim period where various features have been added to the plugin but haven't been released which means that what's in master (the branch people are seeing by default) has some significant differences from the currently released version, which is what is formally supported, but I don't want to extensively document since these features are under active development - as should be evident from the discussion on the PRs and Issues about Pull Request Decoration. I'm making an assumption that anyone building from source to try and use what's on master has some technical knowledge so can work out how to use the plugin from what documentation is available, can read the source code if needed and - very importantly - can troubleshoot issues so they can report potential bugs. When I do release the latest version, I plan on using the repositories Wiki pages to provide some documentation, so am more than happy for anyone who wants to assist with that to provide any relevant contribution.

I know this may not be optimal, but I have to balance my time between developing features, responding to PRs and Issues, reading through Sonarqube source-code to work out what needs implemented, and doing my day job, all whilst trying to have a personal life in there somewhere, so I've made a purposeful decision that the documentation is low priority given my statement in the first paragraph of this response.

**Comment by bmaehr** [comment]
@mc1arke Instead of writing this long text about obvious things I alread know in the same time you would have been able to answer my questions and solve the most important issues of the documentation problem.

**Comment by mc1arke** [comment]
@bmaehr  you may know these things but, as this is a public forum, I'm making it clear to anyone else who reads this issue why the project is as it is, and what the expected next steps are.

**Comment by mc1arke** [comment]
To answer your points:
1. This plugin provides an implementation of the branch analysis interfaces in Sonarqube which allows scanning of individual branches on a project, and comparison of the issues between the scanned branch and its target branch. There are interfaces that are implemented in all 3 components of Sonarqube: Compute Engine (CE), Scanner, and Server. In the current (unreleased) master and SonarQube 8.1 versions, we also allow decoration of Pull Requests so that issues can be reported back to the ALM containing the branch being scanned, and any issues can be highlighted on individual lines of code. This decoration is performed by CE, and supports Bitbucket server, Gitlab (Server and Gitlab.com) and Github (Server and Github.com)
2. You really need to look at Sonarsource's documentation (linked in the README) for how to scan branches for the build system you use. In your case, the most simple case on the released version of the plugin (i.e. no PR decoration) is `mvn sonar:sonar -Dsonar.pullrequest.branch=XXX -Dsonar.pullrequest.base=YYY -Dsonar.pullrequest.key=ZZZ`
3. Enabling Pull Request decoration in a pre-release version of the plugin will depend on which version of the plugin you use, and which version of Sonarqube you're running. As you've not mentioned either of these in your issue, I can't provide any specific details for now. The parameters that are available are still under active development so are not fully documented, but are all visible in the UI either server-wide, or per-project depending on what they are managing. If you can't see these UI settings then this may indicate you've not actually installed the plugin properly.

**Comment by bmaehr** [comment]
So the short answer ist:
1a and 1b) Plugin makes feature branch analyzation work with SonarQube Community Edition
1c) 1.2.0 doesnt support MR decoration, master supports Bitbucket, Gitlab and Github, other branches for other ALM in development
3) 1.2.0 has no settings in web UI because not supporting decoration, master should show them there and make it possible to configure decoration

**Comment by bmaehr** [comment]
If someone is using the gitlab plugin for Jenkins: To make decoration work the correct setting is `-Dsonar.pullrequest.key=$gitlabMergeRequestIid`
